# Workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  release:
    types: [created]
  # Runs on pushes targeting the default branch
  #push:
    #branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  check-codeql:
    name: Check CodeQL Analysis
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Check CodeQL Workflow
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          gh run list --workflow "CodeQL" --json conclusion --jq '.[0].conclusion' > codeql_status.txt
          CODEQL_STATUS=$(cat codeql_status.txt)
          if [[ "$CODEQL_STATUS" != "success" ]]; then
            echo "CodeQL Analysis did not succeed. Exiting..."
            exit 1
          fi
          rm codeql_status.txt

  # Build job
  build:
    runs-on: ubuntu-24.04
    # Require the codeql job to complete successfully before running
    needs: check-codeql
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0

      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.13
        #with:
          #source: ./
          #destination: ./_site

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1

  # Deployment job
  deploy:
    runs-on: ubuntu-24.04
    needs: [build, check-codeql]

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4.0.5
